fix: Kill job when Sbt fails to start

diff --git a/src/commands/sbt_cached.yml b/src/commands/sbt_cached.yml
--- a/src/commands/sbt_cached.yml
+++ b/src/commands/sbt_cached.yml
@@ -70,7 +70,12 @@ steps:
       steps:
         - run:
             name: Background sbt server
-            command: SBT_NATIVE_CLIENT=false sbt
+            command: |
+              set +o pipefail
+              SBT_NATIVE_CLIENT=false sbt
+              if [ ! $? ]; then
+                touch .sbt-failed-to-start
+              fi
             background: true
         - run:
             name: Set SBT_NATIVE_CLIENT env variable
@@ -82,6 +87,10 @@ steps:
 
               while ! ls .bsp/sbt.json 2> /dev/null ;
               do
+                  if [ -f .sbt-failed-to-start ]; then
+                    echo "Sbt failed to start"
+                    exit 1
+                  fi
                   sleep 1
                   echo "Waiting for sbt to start..."
               done
