cleanup

diff --git a/src/jobs/helm_aws.yml b/src/jobs/helm_aws.yml
--- a/src/jobs/helm_aws.yml
+++ b/src/jobs/helm_aws.yml
@@ -136,7 +136,6 @@ steps:
                 for RELEASE in $RELEASES ; do
                   DEPLOYMENTS=$(helm get manifest -n $NAMESPACE $RELEASE | yq eval -o json | jq -r '. | select(.kind == "Deployment") | .metadata.name' | sort -r)
                   for DEPLOYMENT in $DEPLOYMENTS ; do
-                    hasErrors=false
                     if [ << parameters.scale_environment_down >> = true ]; then
                       REPLICA_COUNT=0
                     else
@@ -144,14 +143,12 @@ steps:
                     fi
                     kubectl scale --replicas=$REPLICA_COUNT deployment/$DEPLOYMENT -n $NAMESPACE
                     if [[ << parameters.wait_for_pods_ready >> = true ]]; then
-                      kubectl rollout status deployment/$DEPLOYMENT -n $NAMESPACE --timeout << parameters.wait_for_pods_ready_timeout >> || hasErrors=true
-                      if [[ hasErrors = true ]]; then
-                        error_deployments+=("$DEPLOYMENT")
-                      fi
+                      kubectl rollout status deployment/$DEPLOYMENT -n $NAMESPACE --timeout << parameters.wait_for_pods_ready_timeout >> || error_deployments+=("$DEPLOYMENT")
                     fi
                   done
-                  if [[ ${#error_deployments[@]} != 0 ]]; then
-                    echo "The following deployments failed to be scaled up: " + ${files[*]}
-                    exit 1
                 done
+                if [[ ${#error_deployments[@]} != 0 ]]; then
+                  echo "The following deployments failed to be scaled up:" ${error_deployments[*]}
+                  exit 1
+                fi
               fi
