minor improvements

diff --git a/src/jobs/microk8s_install.yml b/src/jobs/microk8s_install.yml
--- a/src/jobs/microk8s_install.yml
+++ b/src/jobs/microk8s_install.yml
@@ -194,6 +194,10 @@ steps:
               fi
 
               printf "\n\nTrying to run an analysis...."
+
+              # lets give it two minutes to cool down
+              sleep 120
+
               printf "Only works for play crypto secret = \"TEST_STRING_0123456789_0123456789_0123456789_0123456789_0123456789_0123456789_0123456789_0123456789\"\n\n"
 
               # Creating an API token for user with id=1
@@ -202,7 +206,7 @@ steps:
               -c "INSERT INTO \"ApiTokens\" (\"accountId\",\"clientId\",\"secretId\") VALUES  ('1','fc15acbf7b5aab4afe19c588c2ce1e1cc86742a0c08ed7fb540190019059eb0d','cef5fa6242d5c519e59836ee1b7f3afe93864d082ec0b9aaa822072c668a5bff3dab8829bf48159718252e725549701a514896b0efe09136b2f9b3a0ac1721db');"
 
               # Port forward codacy-api
-              sudo microk8s.kubectl port-forward deployment/codacy-api -n codacy 9000 --pod-running-timeout=5m0s &
+              sudo microk8s.kubectl port-forward deployment/codacy-api -n << parameters.namespace >> 9000 --pod-running-timeout=5m0s &
               # wait for port to be ready
               sleep 5
 
@@ -210,13 +214,28 @@ steps:
               curl -i -H "Content-Type: application/json" -H "api-token:fWz6plit8jzFDLylH0tx" --data '{ "url": "https://github.com/DevCodacyTestUser/codacytest" }' http://localhost:9000/2.0/project/create/public
 
               # Wait for project analysed
+              sleep 20
               COUNT=0
               ATTEMPTS=120
               OUT="not found"
-              until $( [[ $OUT == *"Analysed"* ]]  || [[ $COUNT -eq $ATTEMPTS ]]); do
+              until $( [[ $OUT == *'"Analysed"'* ]]  || [[ $COUNT -eq $ATTEMPTS ]]); do
                 OUT=$(curl  -H "Content-Type: application/json" -H "api-token:fWz6plit8jzFDLylH0tx"  http://localhost:9000/2.0/jaime_1/codacytest/commit/f0c9fc5255350d4bfa2f52bfceed6465603a84f1 );
                 echo $OUT;
                 echo -e "$(( COUNT++ ))... \c";
+                printf "\n\n ## WORKER LOGS ## \n\n"
+                sudo microk8s.kubectl logs -l app=worker -c worker --namespace << parameters.namespace >>
                 sleep 10;
               done
-              [[ $COUNT -eq $ATTEMPTS ]] && echo "Could not verify that the analysis ran" && (exit 1)
+              if [[ $COUNT -eq $ATTEMPTS ]]; then
+                echo -e "Could not verify that the analysis ran"
+                printf "\n\nPrint stuff to help debug\n\n"
+
+                printf "\n\n ## NAMESPACE EVENTS ## \n\n"
+                sudo microk8s.kubectl get events --namespace << parameters.namespace >>
+
+                printf "\n\n ## WORKER-MANAGER LOGS ## \n\n"
+                sudo microk8s.kubectl logs deployment/codacy-worker-manager -n << parameters.namespace >>
+
+                echo "Could not verify that the analysis ran"
+                (exit 1)
+              fi
